### ISSUE TITLE
Add capacity to modify current magic comments

### ISSUE THREAD

**Issue by mariomc** [morganney/magic-comments-loader#28]
Hello,

Thank you for the library!

I've been trying to use it, without success, to alter a third-party library that uses magic comments but it seems that the formatter skips changing/adding current existing comments ( see https://github.com/morganney/magic-comments-loader/blob/main/src/formatter.js#L27 )

Is there a workaround that I've missed?

Thank you!

**Comment by morganney** [comment]
Hi, thanks for the feedback and suggestion.

You found the right spot in the code that is blocking your described use case. Right now the loader simply ignores any dynamic import expression that already has comments of any kind.

A nice feature to add would be some global configuration option similar to [`mode`](https://github.com/morganney/magic-comments-loader#mode) and [`match`](https://github.com/morganney/magic-comments-loader#match) that accepted values describing how to deal with dynamic imports that already include comments. Perhaps an option called `comments` with some supported values like `replace`, `append`, `prepend`, and `skip` (the current behavior)? For your particular use case, did you want to overwrite the comments added by the third-party library or add to them?

**Comment by morganney** [comment]
Actually, accepting a value of a callback that receives the current comment (if any) would be great to support as well.

**Comment by mariomc** [comment]
> A nice feature to add would be some global configuration option similar to [`mode`](https://github.com/morganney/magic-comments-loader#mode) and [`match`](https://github.com/morganney/magic-comments-loader#match) that accepted values describing how to deal with dynamic imports that already include comments. Perhaps an option called `comments` with some supported values like `replace`, `append`, `prepend`, and `skip` (the current behavior)? For your particular use case, did you want to overwrite the comments added by the third-party library or add to them?

This library in particular defines its own magic-comments and the use-case would be to change those to manipulate the way those async chunks are named/loaded/grouped.

> Actually, accepting a value of a callback that receives the current comment (if any) would be great to support as well.

I'll try to make that into a feature.

**Comment by morganney** [comment]
I've released [v2.1.0](https://github.com/morganney/magic-comments-loader/releases/tag/v2.1.0) that will allow for working with dynamic imports that already contain comments. You can see the docs for the new [`comments`](https://github.com/morganney/magic-comments-loader#comments) option that provides this feature.

Let me know if you have any questions, I'd be happy to help you out.
